version: '3'

services:
  mysql:
    image: mysql:5.6
    container_name: docker-mysql
    environment:
      MYSQL_DATABASE: users
      MYSQL_USER: monzon
      MYSQL_PASSWORD: monzon15164
      MYSQL_ROOT_PASSWORD: monzon15164
    ports:
      - "3306:3306"
    restart: always